### ISSUE TITLE
FIDO-compliant?

### ISSUE THREAD

**Issue by fjf2002** [pquerna/mod_authn_yubikey#3]
Hello Jens,

what dioes this module actually do? Is it FIDO-compilant?

Sincerely,
fjf2002

**Comment by pquerna** [comment]
This module is not for FDIO-style authenticators.

This module is for use with Yubikeys in "OTP Mode".  The scheme is described here: https://developers.yubico.com/OTP/OTPs_Explained.html

(This scheme predates modern FIDO / U2F)
